spring:
  profiles:
     active: native
  application:
    name: adminservice
  config:
    location: classpath:/config/

server:
  port: 8084
  allowedOrigin: 8080
  ip: localhost

protocol:
  http: http://
  https: https://
  
eureka:
 client:
  serviceUrl:
   defaultZone: http://microservice:thisISthEconnectION2Eureka@${server.ip}:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://${server.ip}:8080/oauth/user
      
services:
  laundryservice: laundryservice
  
rest:
  weekdays: weekdays